main = ".open-next/worker.js"
name = "gearhawk-site"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]

# Assets configuration
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

# KV namespaces (currently commented out as no binding has been defined)
# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "<BINDING_ID>"
